version: "3.8"
name: mysql

services:
  db:
    container_name: db
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=demo
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3307:3306'
